CREATE TABLE colaboradores (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  matricula VARCHAR(30) NOT NULL UNIQUE,
  nome VARCHAR(150) NOT NULL,
  cpf VARCHAR(14) NOT NULL,
  email VARCHAR(180) NOT NULL,
  cargo VARCHAR(120) NOT NULL,
  setor VARCHAR(120) NOT NULL,
  status VARCHAR(20) NOT NULL
      CHECK ( status IN ('Ativo', 'Inativo', 'Afastado'))
);

CREATE TABLE treinamentos (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(30) NOT NULL UNIQUE,
  nome VARCHAR(180) NOT NULL,
  classificacao VARCHAR(60) NOT NULL,
  nr VARCHAR(60),
  carga_horaria VARCHAR(30) NOT NULL,
  validade_meses INTEGER
      CHECK ( validade_meses IS NULL OR validade_meses >= 0),
  status VARCHAR(20) NOT NULL
      CHECK ( status IN ('Ativo', 'Inativo') )
);

CREATE TABLE epis (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(180) NOT NULL,
    ca VARCHAR(30) NOT NULL,
    inclusao DATE NOT NULL,
    validade DATE NOT NULL,
    quantidade INTEGER NOT NULL
        CHECK (quantidade >= 0)
);
